# Generated by Django 4.0.5 on 2022-11-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0022_alter_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
